res50:
  name: Resnet50
  weights_path: dependencies/weigths/Resnet50_Final.pth
  min_sizes: [[16, 32], [64, 128], [256, 512]]
  steps: [8, 16, 32]
  variance: [0.1, 0.2]
  clip: False
  return_layers:
    layer2: 1
    layer3: 2
    layer4: 3
  in_channel: 256
  out_channel: 256
mnet1:
  name: mobilenet0.25
  weights_path: weights/mnet1
  min_sizes: [[16, 32], [64, 128], [256, 512]]
  steps: [8, 16, 32]
  variance: [0.1, 0.2]
  clip: False
  return_layers:
    stage1: 1
    stage2: 2
    stage3: 3
  in_channel: 32
  out_channel: 64
