detector:                           # retina face detector
  image_size: 336                   # image size input to detector. Default=224
  nms_threshold: 0.5                # nms
  conf_threshold: 0.8               # confidence
  minface: 50                       # min face size. Default=50
  device: cuda                       # cpu, cuda
  architecture: mnet1               # res50 (ResNet 50), mnet1 (mobilenet1)
  batch_size: 2                     # for only openvino
embedder:                           # face image to 512D
  image_size: 112                   # input size of emmbeder 
  descriptor_size: &descriptor_size 512
  device: cuda                       # cpu, cuda
  architecture: iresnet34           # iresnet100, iresnet50, iresnet34
  batch_size: 10                    # for only openvino
attributes:                         # face attributes detection
  architecture: yolov5s              # yolov5s, yolov5m, yolov5l, yolov5x
  device: cuda                       # cpu, cuda
  decision_threshold: 0.5
database:                         # faiss database
  descriptor_size: *descriptor_size # database descriptor size
tracking:                         # Join Detection and OpenCV and Embedding tracking
  threshsimilarityinstant: 0.6      # Feature similarity matching between previous frame with current frame
  threshiou: 0.2                    # IOU between opencv tracking with detection
  threshsimilarityiou: 0.2          # Feature similarity when using IOU opencv tracking-detection
  # device: cuda                      # cpu, cuda
evaluter:                           # Face quality evaluter
  ratio0_min: 0.8                   # min of left_eye_to_right_eye/middle_eye_to_middle_mouth distance
  ratio0_max: 1.1                   # max of left_eye_to_right_eye/middle_eye_to_middle_mouth distance
  ratio1_max: 0.15                  # max of nose_to_line_middle_eye_middle_mouth/middle_eye_to_middle_mouth distance
  ratio2_min: 0.35                  # min of evalution nose_to_middle_eye/middle_eye_to_middle_mouth distance
  ratio2_max: 0.75                  # max of evalution nose_to_middle_eye/middle_eye_to_middle_mouth distance
