detector:                         # retina face detector
  image_size: 336                   # image size input to detector. Default=224
  nms_threshold: 0.5                # nms
  conf_threshold: 0.8               # confidence
  minface: 50                       # min face size. Default=50
  device: CPU                     # CPU, GPU, FPGA or MYRIAD
  architecture: mnet1               # res50 (ResNet 50), mnet1 (mobilenet1)

res50:
  name: Resnet50
  weights_path: weights/res50
  image_size: 336 
  output_names:
    - "762"
    - "837"
    - "836"
mnet1:
  name: mobilenet0.25
  weights_path: weights/mnet1
  image_size: 336 
  output_names:
    - "515"
    - "590"
    - "589"
