yolov5:
  weights: weights/yolov5_face_attrs.pt            #model.pt path(s)
  img_size: 224                                     #inference size (pixels)
  conf_thres: 0.25        #object confidence threshold
  iou_thres: 0.45         #IOU threshold for NMS
  device: cuda            #cuda or cpu
  view_img: True          #display results
  classes: 1              #filter by class: --class 0, or --class 0 2 3 , 0:person 1:head
  agnostic_nms: False      #class-agnostic NMS
  augment: False           #augmented inference